import {StyleSheet} from 'react-native';
import {colors, fontSize, radius, spacing} from '@/constants/theme';

export const subscriptionCardStyles = StyleSheet.create({
    card: {
        marginHorizontal: spacing.md,
        marginBottom: spacing.md,
        backgroundColor: colors.surface,
        borderRadius: radius.xl,
        padding: spacing.xl,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
        gap: spacing.md,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.18,
        shadowRadius: 18,
        elevation: 7,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        gap: spacing.md,
    },
    eyebrow: {
        fontFamily: 'PlusJakartaSans-Medium',
        fontSize: fontSize.xs,
        color: colors.textMuted,
        textTransform: 'uppercase',
        letterSpacing: 0.8,
        marginBottom: 2,
    },
    title: {
        fontFamily: 'PlusJakartaSans-Bold',
        fontSize: fontSize.xl,
        color: colors.text,
        flexShrink: 1,
    },
    link: {
        fontFamily: 'PlusJakartaSans-Medium',
        fontSize: fontSize.sm,
        color: colors.accent,
        marginTop: 4,
    },
    highlightValue: {
        fontFamily: 'PlusJakartaSans-ExtraBold',
        fontSize: fontSize.display,
        color: colors.text,
        letterSpacing: -0.4,
        lineHeight: 46,
    },
    helperText: {
        fontFamily: 'PlusJakartaSans-Regular',
        fontSize: fontSize.sm,
        color: colors.textMuted,
        lineHeight: 22,
        maxWidth: '94%',
    },
    addBtn: {
        backgroundColor: colors.accentDim,
        borderRadius: radius.lg,
        borderWidth: 1,
        borderColor: 'rgba(110,231,183,0.14)',
        alignItems: 'center',
        paddingVertical: spacing.sm,
        minHeight: 48,
        justifyContent: 'center',
    },
    addBtnText: {
        fontFamily: 'PlusJakartaSans-Medium',
        fontSize: fontSize.md,
        color: colors.accent,
        letterSpacing: 0.1,
    },
});
